version: '3.8'

services:
  self_service_app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: self_service_app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mifos_network

networks:
  mifos_network:
